In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import time
import h5py
import os,sys
import numpy as np

In [5]:
DSPACK_HOME=os.environ.get("DSPACK_HOME")
if DSPACK_HOME not in sys.path:
    sys.path.append(DSPACK_HOME)

In [7]:
import scripts.fsystem

In [6]:
workdir = "/reg/data/ana03/scratch/zhensu/Experiment/ICH/20201225/"
dnames = ["WT-1", "WT-2", "WT-3", "G150A-1", "G150A-2", "G150A-3", "G150T-1", "G150T-2", "G150T-3"]

In [15]:
data = np.zeros((9,9))

## Get CC1/2
for idx, dname in enumerate(dnames):
    path_dsdata = "%s/data/%s/standard_clean_data_scale_profile_with_pca_map1.dsdata"%(workdir,dname)
    path_phenix = scripts.fsystem.H5manager.reader(path_dsdata,"phenix_merge_stats")
    cc12 = scripts.fsystem.H5manager.reader(path_phenix,"phenix_cc12")
    data[idx,idx] = cc12
    
## Get inter-dataset CC
marker = np.triu(np.ones((9,9)).astype(int), 1)
marker[0:6,6:9] = 0

path_cc_map = "%s/data/CC-MAP/ccmap_standard_clean_data_scale_profile_with_pca.out"%workdir
ccmap = scripts.fsystem.H5manager.reader(path_cc_map,"cc")
index = np.where(marker==1)
data[index] = ccmap[index]

## Print the data
print np.around(data, 2)

[[0.85 0.85 0.87 0.82 0.83 0.85 0.   0.   0.  ]
 [0.   0.78 0.83 0.87 0.8  0.85 0.   0.   0.  ]
 [0.   0.   0.81 0.83 0.88 0.85 0.   0.   0.  ]
 [0.   0.   0.   0.81 0.8  0.83 0.   0.   0.  ]
 [0.   0.   0.   0.   0.76 0.81 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.77 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.82 0.85 0.91]
 [0.   0.   0.   0.   0.   0.   0.   0.84 0.88]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.89]]
